---
title: "Suicidality Among Black Youth"
author: "Xueqing Zhou & Dingxin Lu"
date: '2023-01-17'
output: 
  html_document:
   df_print: paged
   toc: true 
   toc_depth: 2  
   number_sections: false
   toc_float:
     collapsed: true
     smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=FALSE}
## load the libraries
library(readr)
library(survey)
library(dplyr)
library(tidyverse)
library(gtsummary)
library(MASS)
options(survey.lonely.psu="adjust")
```

```{r, message=FALSE}
## read in the data
yrbs_all <- read_csv("C:/Users/surface/OneDrive/Desktop/Master's degree/Summer 2022 CLASS/Capstone/sadc_2019_national.csv")
```

## Data Cleaning

```{r}
## subset black data and correct the outcome variable
black_data <- yrbs_all %>%
  ## filter only "Black or African American"
  filter(race7 == "Black or African American") %>%
  ## correct the outcome variable (1 - Yes, 2 - No)
  mutate(qn28 = replace(qn28, which(qn26 == 2 & qn27 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn26 == 2 & qn27 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn28 == 2), 2)) %>%
  mutate(qn28 = replace(qn28, which(qn29 == 1), 1)) %>%
  mutate(qn27 = replace(qn27, which(qn26 == 2), 2)) %>%
  mutate(qn28 = replace(qn28, which(qn26 == 2), 2)) %>%
  mutate(qn29 = replace(qn29, which(qn26 == 2), 2)) %>%
  mutate(qn26 = replace(qn26, which(qn27 == 1), 1)) %>%
  mutate(qn26 = replace(qn26, which(qn28 == 1), 1)) %>%
  mutate(qn26 = replace(qn26, which(qn29 == 1), 1)) %>%
  #drop_na(qn26:qn29) %>%
  ## change '2 - No' to '0 - No' for better analysis
  mutate(across(qn26:qn29, ~ ifelse(. == 2, 0, .)))
```


## Survey Weighted

```{r}
# weighted design data
yrbsdes <- svydesign(id=~PSU, 
                     weight=~weight, 
                     strata=~stratum, 
                     data=black_data, 
                     nest=TRUE)
yrbsdes_all <- svydesign(id=~PSU, 
                     weight=~weight, 
                     strata=~stratum, 
                     data=yrbs_all, 
                     nest=TRUE)
#tbl_svysummary(data = yrbsdes, include = q26)
#svytotal(~qn26, yrbsdes)
#svymean(~qn26, yrbsdes)
```


## Dependent variables

```{r}
## *should drop ppl with no answers for race*
svytable(~race7 + year, yrbsdes_all, na.action = na.pass, exclude = NULL)
prop.table(svytable(~race7 + year, yrbsdes_all), 2) %>% round(3)
## *should drop NAs for analysis*
## weighted but not adjusted, weighted and adjusted　
svytable(~q26 + year, yrbsdes, na.action = na.pass, exclude = NULL)
svytable(~qn26 + year, yrbsdes, na.action = na.pass, exclude = NULL)
prop.table(svytable(~qn26 + year, yrbsdes), 2) %>% round(3)
svytable(~q27 + year, yrbsdes, na.action = na.pass, exclude = NULL)
svytable(~qn27 + year, yrbsdes, na.action = na.pass, exclude = NULL)
prop.table(svytable(~qn27 + year, yrbsdes), 2) %>% round(3)
svytable(~q28 + year, yrbsdes, na.action = na.pass, exclude = NULL)
svytable(~qn28 + year, yrbsdes, na.action = na.pass, exclude = NULL)
prop.table(svytable(~qn28 + year, yrbsdes), 2) %>% round(3)
svytable(~q29 + year, yrbsdes, na.action = na.pass, exclude = NULL)
svytable(~qn29 + year, yrbsdes, na.action = na.pass, exclude = NULL)
prop.table(svytable(~qn29 + year, yrbsdes), 2) %>% round(3)
```

## Independent variable

```{r}
## sexual identity??
prop.table(svytable(~sexid + year, yrbsdes), 2) %>% round(3)
## sex of sexual contact??
prop.table(svytable(~sexpart + year, yrbsdes), 2) %>% round(3)
## ??bmi: continuous (bmipct: bmi percentile)
## 1993-2019: q13, q15, q16, q18, q57
## 1995-2019: q40, q51, q56
## 1999-2019: q25, q38, q52, q53, q68, q69, q70, q71, q72, q73, q74, q76, q79, q82
## 2001-2019: q19, q54, q86, q89
## 2003-2019: q80, q87
## 2005-2019: q84
## 2007-2019: q44, q75, q88
## 2009-2019: q23
## 2011-2019: q24, q77, q78
## 2013-2019: q10, q11, q21, q22, q43
## 2015-2019: q34, q35, q48, q65, q66
## 2017-2019: q14, q20, q31, q36, q37, q39, q42, q49, q83
## only 2019: q85
q_colnames <- black_data %>%
  select(num_range("q", 8:89), age, sex, grade, bmi, -q26, -q27, -q28, -q29) %>%
  colnames()
for (i in seq_along(q_colnames)){
  FORMULA = as.formula(paste("~",q_colnames[i], "+ year"))
  print(prop.table(svytable(FORMULA, yrbsdes, na.action = na.pass, exclude = NULL), 2) %>% round(3))
}
```

## Raw Count

```{r}
## prevalence of each year (count of each year?)
prev_by_year <- black_data %>% 
  group_by(year) %>%
  summarise(across(qn26:qn29, sum))
## prevalence vs. 4 outcome variables by year
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(year) %>%
  ggplot(aes(outcomes, prevalence, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. 4 Outcome Variables by Year",
       x = "Outcome Variables",
       y = "Prevalence",
       fill = "Year")
## prevalence vs. year by 4 outcome variables
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(outcomes) %>%
  ggplot(aes(as.factor(year), prevalence, fill = outcomes)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. Year by 4 Outcome Variables",
       x = "Year",
       y = "Prevalence",
       fill = "Outcome Variables")
```

## No correction outcome variables

```{r}
blk_data_origin <- yrbs_all %>%
  filter(race7 == "Black or African American") %>%
  drop_na(qn26:qn29) %>%
  ## change '2 - No' to '0 - No' for better analysis
  mutate(across(qn26:qn29, ~ ifelse(. == 2, 0, .)))
## prevalence of each year (count of each year?)
prev <- blk_data_origin %>% 
  group_by(year) %>%
  summarise(across(qn26:qn29, sum))
## prevalence vs. 4 outcome variables by year
prev %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(year) %>%
  ggplot(aes(outcomes, prevalence, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. 4 Outcome Variables by Year",
       x = "Outcome Variables",
       y = "Prevalence",
       fill = "Year")
## prevalence vs. year by 4 outcome variables
prev_by_year %>%
  pivot_longer(qn26:qn29,
               names_to = "outcomes",
               values_to = "prevalence") %>%
  group_by(outcomes) %>%
  ggplot(aes(as.factor(year), prevalence, fill = outcomes)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Prevalence vs. Year by 4 Outcome Variables",
       x = "Year",
       y = "Prevalence",
       fill = "Outcome Variables")
## *should drop ppl with no answer for races*
yrbs_all %>%
  group_by(year) %>%
  mutate(total_num = n()) %>%
  filter(race7 == "Black or African American") %>%
  mutate(black_num = n()) %>%
  filter(!duplicated(year)) %>%
  select(year, total_num, black_num) %>%
  mutate(black_prop = round(black_num / total_num, 3))
table(yrbs_all$race7)
```

## Modelling 

```{r}
# convert age variable to qn1
black_data$qn1 <- substr(black_data$age, 1, 2)
black_data$qn1 <- as.numeric(black_data$qn1)

# convert gender into: male = 0 and female = 1
black_data$qn2[black_data$sex == "Female"] <- 1      
black_data$qn2[black_data$sex == "Male"] <- 0  

# convert grade into numerical variabes
black_data$qn3[black_data$grade == "9th"] <- 0      
black_data$qn3[black_data$grade == "10th"] <- 1 
black_data$qn3[black_data$grade == "11th"] <- 2
black_data$qn3[black_data$grade == "12th"] <- 3 

# QN65 is un-usable, because it is the variable for "During your life, with whom have you had sexual contact?"; It has the selection of male, female, Females and males and I have never had sexual contact  which are not helpful for analysis

# QN66 is "sexual orientation", such as Heterosexual (straight), Gay or lesbian, Bisexual and Not sure.
# convert QN66 to: Heterosexual (straight) = 0; Gay or lesbian = 1; Bisexual = 2; Not sure = NA
black_data$qn66[black_data$q66 == "Heterosexual (straight)"] <- 0      
black_data$qn66[black_data$q66 == "Gay or lesbian"] <- 1  
black_data$qn66[black_data$q66 == "Bisexual"] <- 1
black_data$qn66[black_data$q66 == "Missing"] <- NA 
black_data$qn66[black_data$q66 == "Not sure"] <- NA
```

### QN26

```{r}
# load the package for LASSO regression
library(ISLR)
attach(Hitters)
require(glmnet)
library(plotmo)
library(readr)
library(mice)
library(miselect)

df <- subset(black_data, select = c(year, qn8:qn89, qn1:qn66))
# check missing values
colMeans(is.na(df))
```

This dataset includes lots of missing values, so we need to impute it using the R package mice.

```{r}
set.seed(12345)
# Using the mice defaults for sake of example only.
mids <- mice(df, m = 5, printFlag = FALSE)

# Generate list of completed data.frames
dfs <- lapply(1:5, function(i) complete(mids, action = i))

# Generate list of imputed design matrices and imputed responses
x <- list()
y <- list()
for (i in 1:5) {
    x[[i]] <- as.matrix(dfs[[i]][,c('year', paste0("qn", c(8:25, 30:64, 67:89, 1:3, 66)))])
    y[[i]] <- dfs[[i]]$qn26
}

# Calculate observational weights
pf       <- rep(1, 81)
adWeight <- rep(1, 81)

# Since 'Y' is a binary variable, we use 'family = "binomial"'
fit <- galasso(x, y, pf, adWeight, family = "binomial")

# By default 'coef' returns the betas for (lambda.min , alpha.min)
coef(fit)
```

```{r}
#perform k-fold cross-validation to find optimal lambda value
cv_model <- cv.glmnet(x, y, alpha = 1)

#find optimal lambda value that minimizes test MSE
best_lambda <- cv_model$lambda.min
best_lambda

#produce plot of test MSE by lambda value
plot(cv_model) 

#find coefficients of best model
best_model <- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)
```

```{r}
#include weight in glmnet() == LASSO
#get standard error from somewhere else
res.qn26 <- svyglm(qn26 ~ qn10*factor(year), 
               data = black_data, 
               design = yrbsdes, 
               family = quasibinomial())

summary(res.qn26)
```

